### ISSUE TITLE
Weather update fails on reverse geocoding

### ISSUE THREAD

**Issue by mattrossman** [mattrossman/forecaswatch2#41]
The following snippet currently gets no response from the reverse geocoding service:
https://github.com/mattrossman/forecaswatch2/blob/5c80d0ef9b33b283ea4835f3dce56b049c577157/src/pkjs/weather/provider.js#L62-L72

I'm not sure what the cause for this is. [Here is the free endpoint](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm) that I'm calling, I don't see any obvious notices about changes to the service, but any calls that I try to make get stuck. This might just be a temporary slowdown. Later on I'll look a bit deeper to see if there's any actual changes.

**Comment by PowerScissor** [comment]
Thankyou for looking into this so quickly...and for keeping the project alive in general. There are no good alternative watchfaces for my use case, so hopefully it's just something temporary.

**Comment by arcaderaid** [comment]
"No data :(".  Sad face, indeed!

**Comment by mattrossman** [comment]
End of day update for y'all, I called Esri (company behind ArcGIS) this morning and walked them through the issue. They said that a couple days ago they switched their systems to HTTPS, but even when I tried making requests to the HTTPS endpoint I got a 403 error. They couldn't figure out the problem and took some time to take a closer look. I just got a response back that they figured out the issue, and they will show me when we call again tomorrow.

**Comment by arcaderaid** [comment]
Nice, thanks for the time you put into fixing this so quickly!

**Comment by MilkDX** [comment]
Thanks for getting onto it. 
It's my daily watchface and is already greatly missed.

**Comment by polo421** [comment]
Hello, this is awesome that you are even trying to get this fixed. I looked but was unsuccessful, is there a place I could donate to buy you a beer?

**Comment by mattrossman** [comment]
Resolved in [v1.14.0](https://github.com/mattrossman/forecaswatch2/releases/tag/v1.14.0). Thanks everyone for letting me know about the issue, I haven't been wearing my Pebble much during the quarantine.

By the way, the issue was in fact just HTTPS, but in my testing I forgot to include the `f=json` parameter 🤦

@polo421 I'm glad you enjoy the watchface. I encourage you to donate to an org like [AFSP](https://afsp.org/) instead, but since you're not the first person to bring this up I've also added a [tip jar](https://paypal.me/mttrssmn) to the README.

**Comment by polo421** [comment]
I donated to both. Thanks for being a cool dude.

**Comment by vukisoft** [comment]
Rebble app store still shows v1.8, how do I upgrade manually?

**Comment by vukisoft** [comment]
Will this ever make to rebble.io app store? It still shows v1.8.0

**Comment by mattrossman** [comment]
@vukisoft Sure, I just submitted the updated bundle to @joshua on Discord. Unfortunately app submission is still a manual process by the Rebble team, so it might take a couple days before it shows up on the store.

**Comment by vukisoft** [comment]
It started failing again, last successful update was yesterday 17:31
Any idea why?

**Comment by mattrossman** [comment]
@vukisoft It's not failing on my end (tested both providers), perhaps try deleting and reinstalling it?

**Comment by PowerScissor** [comment]
Anyone have any sideloading tips on Android 10?

While I refresh the Rebble appstore and wait for it to be available I've been trying to open the .pbw file with all the recommended file explorers (I've tried about 20 including Amaze & Dropbox) and can't get Pebble app to show up as an option.

How are you guys that have successfully sideloaded this updated face accomplishing it?

**Comment by vukisoft** [comment]
Reinstalled but I get the same - "No data".

@PowerScissor I used File Manager+, but it did not just offer Pebble. I had to do something extra .. which I can't remember what is was, but it was inside the file manager .. but had to do only once, maybe associating the extension the the app? Now second time it already offers Pebble app to open the file.

**Comment by vukisoft** [comment]
@PowerScissor Does it help if you enable developer connections in Pebble app?

**Comment by mattrossman** [comment]
@PowerScissor [Cx File Explorer](https://play.google.com/store/apps/details?id=com.cxinventor.file.explorer) is working for me on Android 10, it gives the option for "Pebble" app after clicking on a `.pbw` file. I'll make a note of the recent issues w/ Amaze in the README.

@vukisoft Can you send me an [email](mailto:rossman@gatech.edu) and we can debug further there?

**Comment by PowerScissor** [comment]
Thankyou! Cx worked!

Man, I've been installing file explorers like crazy the last 2 days...Cx worked right away.

**Comment by mattrossman** [comment]
The Rebble store is now showing version 1.14.0
